version = 0.1
[default.pipeline_bootstrap.parameters]
pipeline_user = "arn:aws:iam::525636320068:user/aws-sam-cli-managed-Hom-pipeline-resou-PipelineUser-YyARPfzHy5nk"
permissions_provider = "AWS IAM"

[Hom.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::525636320068:role/aws-sam-cli-managed-Hom-pipel-PipelineExecutionRole-DMOA34YoyzoG"
cloudformation_execution_role = "arn:aws:iam::525636320068:role/aws-sam-cli-managed-Hom-p-CloudFormationExecutionRo-z9gsHGMCPBWV"
artifacts_bucket = "aws-sam-cli-managed-hom-pipeline-r-artifactsbucket-wcyfqlsxpnfl"
image_repository = ""
region = "us-east-1"
